### ISSUE TITLE
Inside Co.Meta App Edit

### ISSUE THREAD

**Issue by tankhashobhit** [cometa-rocks/cometa#24]
@raro42 @ArslanSB 
1. When you click on Help in the middle of the screen, it should take you to the steps section and not the website. Please rectify. - This one should be looked at now.
2. When you click on the tutorial, it takes you to a Spanish video. As we are dealing with a global audience, please insert a new video in English. - This can be looked at later.

![Screenshot (2)](https://github.com/cometa-rocks/cometa/assets/142929527/9089696c-01e3-43dd-ab8e-d930d16f9900)

**Comment by raro42** [comment]
May be you would like to prepare the video?

Happy to change the link.

**Comment by tankhashobhit** [comment]
This is not my area. Marketing will handle this.

**Comment by tankhashobhit** [comment]
The task has been mailed to Mayank for the content marketer in place.
